{{ if .Values.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Namespace}}
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-secret
  annotations:
    kubernetes.io/service-account.name: {{.Release.Namespace}}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin
subjects:
- kind: ServiceAccount
  name: {{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: ""
{{ end }}
