apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waitfor-grant
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: waitfor-reader
  apiGroup: ""
